### ISSUE TITLE
New predatory journal - Journal of Genetic Mutation Disorder

### ISSUE THREAD

**Issue by SichongP** [stop-predatory-journals/stop-predatory-journals.github.io#15]
Came across a paper which led me to this journal:
http://www.annexpublishers.com/journals/journal-of-genetic-mutation-disorders/jhome.php

The publisher is Annex Publishers, which is on predatory publisher's list already. to further validate, the address listed on the website (2361 Rolling Fork Circle #107 Herndon, VA) is a residential address.

**Comment by j-tamad** [comment]
Good to know. I edit and help Chinese and other ESL authors/investigators with publication, so this is really useful. They are on this list: https://beallslist.weebly.com/
